poke_names = {

    "Bulbasaur" : "1.png",
    "Ivysaur"   : "2.png",
    "Vensaur"   : "3.png",
    "Charmander": "4.png",
    "Charmeleon": "5.png",
    "Charizard" : "6.png",
    "Squirtle"  : "7.png",
    "Wartortle" : "8.png",
    "Blastoise" : "9.png",
    "Caterpie"  : "10.png",
    "Metapod"   : "11.png",
    "Butterfree": "12.png",
    "Weedle"    : "13.png",
    "Kakuna"    : "14.png",
    "Beedrill"  : "15.png",
    "Pidgey"    : "16.png",
    "Pidgeotto" : "17.png",
    "Pidgeot"   : "18.png",
    "Rattata"   : "19.png",
    "Raticate"  : "20.png",
    "Spearow"   : "21.png",
    "Fearow"    : "22.png",
    "Ekans"     : "23.png",
    "Arbok"     : "24.png",
    "Pikachu"   : "25.png",
    "Raichu"    : "26.png",
    "Sandshrew" : "27.png",
    "Sandslash" : "28.png",
    "Nidoran F" : "29.png",
    "Nidorina"  : "30.png",
    "Nidoqueen" : "31.png",
    "Nidoran M" : "32.png",
    "Nidorino"  : "33.png",
    "Nidoking"  : "34.png",
    "Clefairy"  : "35.png",
    "Clefable"  : "36.png",
    "Vulpix"    : "37.png",
    "Ninetales" : "38.png",
    "Jigglypuff": "39.png",
    "Wigglytuff": "40.png",
    "Zubat"     : "41.png",
    "Golbat"    : "42.png",
    "Oddish"    : "43.png",
    "Gloom"     : "44.png",
    "Vileplume" : "45.png",
    "Paras"     : "46.png",
    "Parasect"  : "47.png",
    "Venonat"   : "48.png",
    "Venomoth"  : "49.png",
    "Diglett"   : "50.png",
    "Dugtrio"   : "51.png",
    "Meowth"    : "52.png",
    "Persian"   : "53.png",
    "Psyduck"   : "54.png",
    "Golduck"   : "55.png",
    "Mankey"    : "56.png",
    "Primeape"  : "57.png",
    "Growlithe" : "58.png",
    "Arcanine"  : "59.png",
    "Poliwag"   : "60.png",
    "Poliwhirl" : "61.png",
    "Poliwrath" : "62.png",
    "Abra"      : "63.png",
    "Kadabra"   : "64.png",
    "Alakazam"  : "65.png",
    "Machop"    : "66.png",
    "Machoke"   : "67.png",
    "Machamp"   : "68.png",
    "Bellsprout": "69.png",
    "Weepinbell": "70.png",
    "Victreebel": "71.png",
    "Tentacool" : "72.png",
    "Tentacruel": "73.png",
    "Geodude"   : "74.png",
    "Graveler"  : "75.png",
    "Golem"     : "76.png",
    "Ponyta"    : "77.png",
    "Rapidash"  : "78.png",
    "Slowpoke"  : "79.png",
    "Slowbro"   : "80.png",
    "Magnemite" : "81.png",
    "Magneton"  : "82.png",
    "Farfetch'd": "83.png",
    "Doduo"     : "84.png",
    "Dodrio"    : "85.png",
    "Seel"      : "86.png",
    "Dewgong"   : "87.png",
    "Grimer"    : "88.png",
    "Muk"       : "89.png",
    "Shellder"  : "90.png",
    "Cloyster"  : "91.png",
    "Gastly"    : "92.png",
    "Haunter"   : "93.png",
    "Gengar"    : "94.png",
    "Onix"      : "95.png",
    "Drowzee"   : "96.png",
    "Hypno"     : "97.png",
    "Krabby"    : "98.png",
    "Kingler"   : "99.png",
    "Voltorb"   : "100.png",
    "Electrode" : "101.png",
    "Exeggcute" : "102.png",
    "Exeggutor" : "103.png",
    "Cubone"    : "104.png",
    "Marowak"   : "105.png",
    "Hitmonlee" : "106.png",
    "Hitmonchan": "107.png",
    "Lickitung" : "108.png",
    "Koffing"   : "109.png",
    "Weezing"   : "110.png",
    "Rhyhorn"   : "111.png",
    "Rhydon"    : "112.png",
    "Chansey"   : "113.png",
    "Tangela"   : "114.png",
    "Kangaskhan": "115.png",
    "Horsea"    : "116.png",
    "Seadra"    : "117.png",
    "Goldeen"   : "118.png",
    "Seaking"   : "119.png",
    "Staryu"    : "120.png",
    "Starmie"   : "121.png",
    "Mr. Mime"  : "122.png",
    "Scyther"   : "123.png",
    "Jynx"      : "124.png",
    "Electabuzz": "125.png",
    "Magmar"    : "126.png",
    "Pinsir"    : "127.png",
    "Tauros"    : "128.png",
    "Magikarp"  : "129.png",
    "Gyarados"  : "130.png",
    "Lapras"    : "131.png",
    "Ditto"     : "132.png",
    "Eevee"     : "133.png",
    "Vaporeon"  : "134.png",
    "Jolteon"   : "135.png",
    "Flareon"   : "136.png",
    "Porygon"   : "137.png",
    "Omanyte"   : "138.png",
    "Omastar"   : "139.png",
    "Kabuto"    : "140.png",
    "Kabutops"  : "141.png",
    "Aerodactyl": "142.png",
    "Snorlax"   : "143.png",
    "Articuno"  : "144.png",
    "Zapdos"    : "145.png",
    "Moltres"   : "146.png",
    "Dratini"   : "147.png",
    "Dragonair" : "148.png",
    "Dragonite" : "149.png",
    "Mewtwo"    : "150.png",
    "Mew"       : "151.png",
    "Chikorita" : "152.png",
    "Bayleef"   : "153.png",
    "Meganium"  : "154.png",
    "Cyndaquil" : "155.png",
    "Quilava"   : "156.png",
    "Typhlosion": "157.png",
    "Totodile"  : "158.png",
    "Feraligatr": "159.png",
    "Sentret"   : "160.png",
    "Furret"    : "161.png",
    "Hoothoot"  : "162.png",
    "Noctowl"   : "163.png",
    "Ledyba"    : "164.png",
    "Ledian"    : "165.png",
    "Spinarak"  : "166.png",
    "Ariados"   : "167.png",
    "Ariados"   : "168.png",
    "Crobat"    : "169.png",
    "Chinchou"  : "170.png",
    "Lanturn"   : "171.png",
    "Pichu"     : "172.png",
    "Cleffa"    : "173.png",
    "Igglybuff" : "174.png",
    "Togepi"    : "175.png",
    "Togetic"   : "176.png",
    "Natu"      : "177.png",
    "Xatu"      : "178.png",
    "Mareep"    : "179.png",
    "Flaaffy"   : "180.png",
    "Ampharos"  : "181.png",
    "Bellossom" : "182.png",
    "Marill"    : "183.png",
    "Azumarill" : "184.png",
    "Sudowoodo" : "185.png",
    "Politoed"  : "186.png",
    "Hoppip"    : "187.png",
    "Skiploom"  : "188.png",
    "Jumpluff"  : "189.png",
    "Aipom"     : "190.png",
    "Sunkern"   : "191.png",
    "Sunflora"  : "192.png",
    "Yanma"     : "193.png",
    "Wooper"    : "194.png",
    "Quagsire"  : "195.png",
    "Espeon"    : "196.png",
    "Umbreon"   : "197.png",
    "Murkrow"   : "198.png",
    "Slowking"  : "199.png",
    "misdreavus": "200.png",
    "Unown"     : "201.png",
    "Wobbuffet" : "202.png",
    "Girafarig" : "203.png",
    "Pineco"    : "204.png",
    "Forretress": "205.png",
    "Dunsparce" : "206.png",
    "Gligar"    : "207.png",
    "Steelix"   : "208.png",
    "Snubbull"  : "209.png",
    "Granbull"  : "210.png",
    "Qwilfish"  : "211.png",
    "Scizor"    : "212.png",
    "Shuckle"   : "213.png",
    "Heracross" : "214.png",
    "Sneasel" : "215.png",
    "Teddiursa" : "216.png",
    "Ursaring" : "217.png",
    "Slugma" : "218.png",
    "Magcargo" : "219.png",
    "Swinub" : "220.png",
    "Piloswine" : "221.png",
    "Corsola" : "222.png",
    "Remoraid" : "223.png",
    "Octillery" : "224.png",
    "Delibird" : "225.png",
    "Mantine" : "226.png",
    "Skarmory" : "227.png",
    "Houndour" : "228.png",
    "Houndoom" : "229.png",
    "Kingdra" : "230.png",
    "Phanpy" : "231.png",
    "Donphan" : "232.png",
    "Porygon2" : "233.png",
    "Stantler" : "234.png",
    "Smeargle" : "235.png",
    "Tyrouge" : "236.png",
    "Hitmontop" : "237.png",
    "Smoochum" : "238.png",
    "Elekid" : "239.png",
    "Magby" : "240.png",
    "Miltank" : "241.png",
    "Blissey" : "242.png",
    "Raikou" : "243.png",
    "Entei" : "244.png",
    "Suicune" : "245.png",
    "Lavitar" : "246.png",
    "Pupitar" : "247.png",
    "Tyranitar" : "248.png",
    "Lugia" : "249.png",
    "Ho-Oh" : "250.png",
    "Celebi" : "251.png",
    "Treecko" : "252.png",
    "Grovyle" : "253.png",
    "Sceptile" : "254.png",
    "Torchic" : "255.png",
    "Combusken" : "256.png",
    "Blaziken" : "257.png",
    "Mudkip" : "258.png",
    "Marshtomp" : "259.png",
    "Swampert" : "260.png",
    "Poochyena" : "261.png",
    "Mightyena" : "262.png",
    "Zigzagoon" : "263.png",
    "Linoone" : "264.png",
    "Wurmple" : "265.png",
    "Silcoon" : "266.png",
    "Beautifly" : "267.png",
    "Cascoon" : "268.png",
    "Dustox" : "269.png",
    "Lotad" : "270.png",
    "Lombre" : "271.png",
    "Ludicolo" : "272.png",
    "Seedot" : "273.png",
    "Nuzleaf" : "274.png",
    "Shiftry" : "275.png",
    "Taillow" : "276.png",
    "Swellow" : "277.png",
    "Wingull" : "278.png",
    "Pelipper" : "279.png",
    "Ralts" : "280.png",
    "Kirlia" : "281.png",
    "Gardevoir" : "282.png",
    "Surskit" : "283.png",
    "Masquerain" : "284.png",
    "Shroomish" : "285.png",
    "Breloom" : "286.png",
    "Slakoth" : "287.png",
    "Vigoroth" : "288.png",
    "Slaking" : "289.png",
    "Nincada" : "290.png",
    "Ninjask" : "291.png",
    "Shedinja" : "292.png",
    "Whismur" : "293.png",
    "Loudred" : "294.png",
    "Exploud" : "295.png",
    "Makuhita" : "296.png",
    "Hariyama" : "297.png",
    "Azurill" : "298.png",
    "Nosepass" : "299.png",
    "Skitty" : "300.png",
    "Delcatty" : "301.png",
    "Sableye" : "302.png",
    "Mawile" : "303.png",
    "Aron" : "304.png",
    "Lairon" : "305.png",
    "Aggron" : "306.png",
    "Meditite" : "307.png",
    "Medicham" : "308.png",
    "Electrike" : "309.png",
    "Manectric" : "310.png",
    "Plusle" : "311.png",
    "Minum" : "312.png",
    "Volbeat" : "313.png",
    "Illumise" : "314.png",
    "Roselia" : "315.png",
    "Gulpin" : "316.png",
    "Swalot" : "317.png",
    "Carvanha" : "318.png",
    "Sharpedo" : "319.png",
    "Wailmer" : "320.png",
    "Wailord" : "321.png",
    "Numel" : "322.png",
    "Camerupt" : "323.png",
    "Torkoal" : "324.png",
    "Spoink" : "325.png",
    "Grumpig" : "326.png",
    "Spinda" : "327.png",
    "Trapinch" : "328.png",
    "Vibrava" : "329.png",
    "Flygon" : "330.png",
    "Cacnea" : "331.png",
    "Cacturne" : "332.png",
    "Swablu" : "333.png",
    "Altaria" : "334.png",
    "Zangoose" : "335.png",
    "Seviper" : "336.png",
    "Lunatone" : "337.png",
    "Solrock" : "338.png",
    "Barboach" : "339.png",
    "Wiscash" : "340.png",
    "Corphish" : "341.png",
    "Crawdaunt" : "342.png",
    "Baltoy" : "343.png",
    "Claydol" : "344.png",
    "Lileep" : "345.png",
    "Cradily" : "346.png",
    "Anorith" : "347.png",
    "Armaldo" : "348.png",
    "Feebas" : "349.png",
    "Milotic" : "350.png",
    "Castform" : "351.png",
    "Kecleon" : "352.png",
    "Shuppet" : "353.png",
    "Banette" : "354.png",
    "Duskull" : "355.png",
    "Dusclops" : "356.png",
    "Tropius" : "357.png",
    "Chimecho" : "358.png",
    "Absol" : "359.png",
    "Wynaut" : "360.png",
    "Snorunt" : "361.png",
    "Glalie" : "362.png",
    "Spheal" : "363.png",
    "Sealeo" : "364.png",
    "Walrein" : "365.png",
    "Clamperl" : "366.png",
    "Huntail" : "367.png",
    "Gorebyss" : "368.png",
    "Relicanth" : "369.png",
    "Luvdisc" : "370.png",
    "Bagon" : "371.png",
    "Shelgon" : "372.png",
    "Salamence" : "373.png",
    "Beldum" : "374.png",
    "Metang" : "375.png",
    "Metagross" : "376.png",
    "Regirock" : "377.png",
    "Regice" : "378.png",
    "Registeel" : "379.png",
    "Latias" : "380.png",
    "Latios" : "381.png",
    "Kyogre" : "382.png",
    "Groudon" : "383.png",
    "Rayquaza" : "384.png",
    "Jirachi" : "385.png",
    "Deoxys" : "386.png",
    "Turtwig" : "387.png",
    "Grotle" : "388.png" ,
    "Torterra" : "389.png" , 
    "Chimchar" : "390.png" , 
    "Monferno" : "391.png" , 
    "Infernape" : "392.png" ,
    "Piplup" : "393.png" ,   
    "Prinplup" : "394.png" , 
    "Empoleon" : "395.png" , 
    "Starly" : "396.png" ,
    "Staravia" : "397.png" ,
    "Staraptor" : "398.png" ,
    "Bidoof" : "399.png" ,
    "Babarel" : "400.png" ,
    "Kricketot" : "401.png" ,
    "Kricketune" : "402.png" ,
    "Shinx" : "403.png" ,
    "Luxio" : "404.png" ,
    "Luxray" : "405.png" ,
    "Budew" : "406.png" ,
    "Roserade" : "407.png" ,
    "Cranidos" : "408.png" ,
    "Rampardos" : "409.png" ,
    "Shieldon" : "410.png" ,
    "Bastiodon" : "411.png" ,
    "Burmy" : "412.png" ,
    "Wormadam" : "413.png" ,
    "Mothim" : "414.png" ,
    "Combee" : "415.png" ,
    "Vespiquen" : "416.png" ,
    "Pachirisu" : "417.png" ,
    "Buizel" : "418.png" ,
    "Floatzel" : "419.png" ,
    "Cherubi" : "420.png" ,
    "Cherrim" : "421.png" ,
    "Shellos" : "422.png" ,
    "Gastrodon" : "423.png" ,
    "Ambipom" : "424.png" ,
    "Drifloon" : "425.png" ,
    "Drifblim" : "426.png" ,
    "Buneary" : "427.png" ,
    "Lopunny" : "428.png" ,
    "Mismagius" : "429.png" ,
    "Honchkrow" : "430.png" ,
    "Glameow" : "431.png" ,
    "Purugly" : "432.png" ,
    "Chingling" : "433.png" ,
    "Stunky" : "434.png" ,
    "Stunktank" : "435.png" ,
    "Bronzor" : "436.png" ,
    "Bronzong" : "437.png" ,
    "Bonsly" : "438.png" ,
    "Mime Jr." : "388.png" ,
    "Happiny" : "389.png" ,  
    "Chatot" : "390.png" ,   
    "Spiritomb" : "391.png" ,
    "Gible" : "392.png" ,    
    "Gibite" : "393.png" ,   
    "Garchomp" : "394.png" , 
    "Munchlax" : "395.png" ,
    "Riolu" : "396.png" ,
    "Lucario" : "397.png" ,
    "Hippopotas" : "398.png" ,
    "Hippowdon" : "399.png" ,
    "Skorupi" : "400.png" ,
    "Drapion" : "401.png" ,
    "Croagunk" : "402.png" ,
    "Toxicroak" : "403.png" ,
    "Carnivine" : "404.png" ,
    "Finneon" : "405.png" ,
    "Lumineon" : "406.png" ,
    "Mantyke" : "407.png" ,
    "Snover" : "408.png" ,
    "Abomasnow" : "409.png" ,
    "Weavile" : "410.png" ,
    "Magnezone" : "411.png" ,
    "Lickilicky" : "412.png" ,
    "Rhyperior" : "413.png" ,
    "Tangrowth" : "414.png" ,
    "Electivire" : "415.png" ,
    "Magmortar" : "416.png" ,
    "Togekiss" : "417.png" ,
    "Yanmega" : "418.png" ,
    "Leafeon" : "419.png" ,
    "Glaceon" : "420.png" ,
    "Gliscor" : "421.png" ,
    "Mamoswine" : "422.png" ,
    "Porygon-z" : "423.png" ,
    "Gallade" : "424.png" ,
    "Probopass" : "425.png" ,
    "Dusknoir" : "426.png" ,
    "Frosslass" : "427.png" ,
    "Rotom" : "428.png" ,
    "Uxie" : "429.png" ,
    "Mesprit" : "430.png" ,
    "Azelf" : "431.png" ,
    "Dialga" : "432.png" ,
    "Palkia" : "433.png" ,
    "Heatran" : "434.png" ,
    "Regigigas" : "435.png" ,
    "Giratina" : "436.png" ,
    "Cresselia" : "437.png" ,
    "Phione" : "438.png" ,
    "Manaphy" : "439.png" ,
    "Darkrai" : "440.png" ,
    "Shaymin" : "441.png" ,
    "Arceus" : "442.png" ,
}