# ----------------------------------------------------------------------------------------
# Author: Kevin Lu
# Date: 10/28/2019
# File: pokemonNames.py
# Purpose: Hash table (dictionary) for pokemon names. This gives us a O(1) lookup time which is important.
# Modification: - Added first generation of pokemons
# ----------------------------------------------------------------------------------------


pokemonNames = {

    "Bulbasaur" : "1.png",
    "Ivysaur"   : "2.png",
    "Vensaur"   : "3.png",
    "Charmander": "4.png",
    "Charmeleon": "5.png",
    "Charizard" : "6.png",
    "Squirtle"  : "7.png",
    "Wartortle" : "8.png",
    "Blastoise" : "9.png",
    "Caterpie"  : "10.png",
    "Metapod"   : "11.png",
    "Butterfree": "12.png",
    "Weedle"    : "13.png",
    "Kakuna"    : "14.png",
    "Beedrill"  : "15.png",
    "Pidgey"    : "16.png",
    "Pidgeotto" : "17.png",
    "Pidgeot"   : "18.png",
    "Rattata"   : "19.png",
    "Raticate"  : "20.png",
    "Spearow"   : "21.png",
    "Fearow"    : "22.png",
    "Ekans"     : "23.png",
    "Arbok"     : "24.png",
    "Pikachu"   : "25.png",
    "Raichu"    : "26.png",
    "Sandshrew" : "27.png",
    "Sandslash" : "28.png",
    "Nidoran F" : "29.png",
    "Nidorina"  : "30.png",
    "Nidoqueen" : "31.png",
    "Nidoran M" : "32.png",
    "Nidorino"  : "33.png",
    "Nidoking"  : "34.png",
    "Clefairy"  : "35.png",
    "Clefable"  : "36.png",
    "Vulpix"    : "37.png",
    "Ninetales" : "38.png",
    "Jigglypuff": "39.png",
    "Wigglytuff": "40.png",
    "Zubat"     : "41.png",
    "Golbat"    : "42.png",
    "Oddish"    : "43.png",
    "Gloom"     : "44.png",
    "Vileplume" : "45.png",
    "Paras"     : "46.png",
    "Parasect"  : "47.png",
    "Venonat"   : "48.png",
    "Venomoth"  : "49.png",
    "Diglett"   : "50.png",
    "Dugtrio"   : "51.png",
    "Meowth"    : "52.png",
    "Persian"   : "53.png",
    "Psyduck"   : "54.png",
    "Golduck"   : "55.png",
    "Mankey"    : "56.png",
    "Primeape"  : "57.png",
    "Growlithe" : "58.png",
    "Arcanine"  : "59.png",
    "Poliwag"   : "60.png",
    "Poliwhirl" : "61.png",
    "Poliwrath" : "62.png",
    "Abra"      : "63.png",
    "Kadabra"   : "64.png",
    "Alakazam"  : "65.png",
    "Machop"    : "66.png",
    "Machoke"   : "67.png",
    "Machamp"   : "68.png",
    "Bellsprout": "69.png",
    "Weepinbell": "70.png",
    "Victreebel": "71.png",
    "Tentacool" : "72.png",
    "Tentacruel": "73.png",
    "Geodude"   : "74.png",
    "Graveler"  : "75.png",
    "Golem"     : "76.png",
    "Ponyta"    : "77.png",
    "Rapidash"  : "78.png",
    "Slowpoke"  : "79.png",
    "Slowbro"   : "80.png",
    "Magnemite" : "81.png",
    "Magneton"  : "82.png",
    "Farfetch'd": "83.png",
    "Doduo"     : "84.png",
    "Dodrio"    : "85.png",
    "Seel"      : "86.png",
    "Dewgong"   : "87.png",
    "Grimer"    : "88.png",
    "Muk"       : "89.png",
    "Shellder"  : "90.png",
    "Cloyster"  : "91.png",
    "Gastly"    : "92.png",
    "Haunter"   : "93.png",
    "Gengar"    : "94.png",
    "Onix"      : "95.png",
    "Drowzee"   : "96.png",
    "Hypno"     : "97.png",
    "Krabby"    : "98.png",
    "Kingler"   : "99.png",
    "Voltorb"   : "100.png",
    "Electrode" : "101.png",
    "Exeggcute" : "102.png",
    "Exeggutor" : "103.png",
    "Cubone"    : "104.png",
    "Marowak"   : "105.png",
    "Hitmonlee" : "106.png",
    "Hitmonchan": "107.png",
    "Lickitung" : "108.png",
    "Koffing"   : "109.png",
    "Weezing"   : "110.png",
    "Rhyhorn"   : "111.png",
    "Rhydon"    : "112.png",
    "Chansey"   : "113.png",
    "Tangela"   : "114.png",
    "Kangaskhan": "115.png",
    "Horsea"    : "116.png",
    "Seadra"    : "117.png",
    "Goldeen"   : "118.png",
    "Seaking"   : "119.png",
    "Staryu"    : "120.png",
    "Starmie"   : "121.png",
    "Mr. Mime"  : "122.png",
    "Scyther"   : "123.png",
    "Jynx"      : "124.png",
    "Electabuzz": "125.png",
    "Magmar"    : "126.png",
    "Pinsir"    : "127.png",
    "Tauros"    : "128.png",
    "Magikarp"  : "129.png",
    "Gyarados"  : "130.png",
    "Lapras"    : "131.png",
    "Ditto"     : "132.png",
    "Eevee"     : "133.png",
    "Vaporeon"  : "134.png",
    "Jolteon"   : "135.png",
    "Flareon"   : "136.png",
    "Porygon"   : "137.png",
    "Omanyte"   : "138.png",
    "Omastar"   : "139.png",
    "Kabuto"    : "140.png",
    "Kabutops"  : "141.png",
    "Aerodactyl": "142.png",
    "Snorlax"   : "143.png",
    "Articuno"  : "144.png",
    "Zapdos"    : "145.png",
    "Moltres"   : "146.png",
    "Dratini"   : "147.png",
    "Dragonair" : "148.png",
    "Dragonite" : "149.png",
    "Mewtwo"    : "150.png",
    "Mew"       : "151.png" 
}